module Reference
 MAPPING = [
    { book_number: 1, book_name: 'Genesis', num_chapters: 50, abbreviation: 'Gen.', ref_code: 'Gen'},
    { book_number: 2, book_name: 'Exodus', num_chapters: 40, abbreviation: 'Exo.', ref_code: 'Exo'},
    { book_number: 3, book_name: 'Leviticus', num_chapters: 27, abbreviation: 'Lev.', ref_code: 'Lev'},
    { book_number: 4, book_name: 'Numbers', num_chapters: 36, abbreviation: 'Num.', ref_code: 'Num'},
    { book_number: 5, book_name: 'Deuteronomy', num_chapters: 34, abbreviation: 'Deut.', ref_code: 'Deu'},
    { book_number: 6, book_name: 'Joshua', num_chapters: 24, abbreviation: 'Josh.', ref_code: 'Jos'},
    { book_number: 7, book_name: 'Judges', num_chapters: 21, abbreviation: 'Judg.', ref_code: 'Jud'},
    { book_number: 8, book_name: 'Ruth', num_chapters: 4, abbreviation: 'Ruth', ref_code: 'Rut'},
    { book_number: 9, book_name: '1 Samuel', num_chapters: 31, abbreviation: '1 Sam.', ref_code: 'FSa'},
    { book_number: 10, book_name: '2 Samuel', num_chapters: 24, abbreviation: '2 Sam.', ref_code: 'SSa'},
    { book_number: 11, book_name: '1 Kings', num_chapters: 22, abbreviation: '1 Kings', ref_code: 'FKi'},
    { book_number: 12, book_name: '2 Kings', num_chapters: 25, abbreviation: '2 Kings', ref_code: 'SKi'},
    { book_number: 13, book_name: '1 Chronicles', num_chapters: 29, abbreviation: '1 Chron.', ref_code: 'FCh'},
    { book_number: 14, book_name: '2 Chronicles', num_chapters: 36, abbreviation: '2 Chron.', ref_code: 'SCh'},
    { book_number: 15, book_name: 'Ezra', num_chapters: 10, abbreviation: 'Ezra', ref_code: 'Ezr'},
    { book_number: 16, book_name: 'Nehemiah', num_chapters: 13, abbreviation: 'Neh.', ref_code: 'Neh'},
    { book_number: 17, book_name: 'Esther', num_chapters: 10, abbreviation: 'Esth.', ref_code: 'Est'},
    { book_number: 18, book_name: 'Job', num_chapters: 42, abbreviation: 'Job', ref_code: 'Job'},
    { book_number: 19, book_name: 'Psalms', num_chapters: 150, abbreviation: 'Psa.', ref_code: 'Psa'},
    { book_number: 20, book_name: 'Proverbs', num_chapters: 31, abbreviation: 'Prov.', ref_code: 'Pro'},
    { book_number: 21, book_name: 'Ecclesiastes', num_chapters: 12, abbreviation: 'Eccl.', ref_code: 'Ecc'},
    { book_number: 22, book_name: 'Song of Solomon', num_chapters: 8, abbreviation: 'S.S.', ref_code: 'Son'},
    { book_number: 23, book_name: 'Isaiah', num_chapters: 66, abbreviation: 'Isa.', ref_code: 'Isa'},
    { book_number: 24, book_name: 'Jeremiah', num_chapters: 52, abbreviation: 'Jer.', ref_code: 'Jer'},
    { book_number: 25, book_name: 'Lamentations', num_chapters: 5, abbreviation: 'Lam.', ref_code: 'Lam'},
    { book_number: 26, book_name: 'Ezekiel', num_chapters: 48, abbreviation: 'Ezek.', ref_code: 'Eze'},
    { book_number: 27, book_name: 'Daniel', num_chapters: 12, abbreviation: 'Dan.', ref_code: 'Dan'},
    { book_number: 28, book_name: 'Hosea', num_chapters: 14, abbreviation: 'Hosea', ref_code: 'Hos'},
    { book_number: 29, book_name: 'Joel', num_chapters: 3, abbreviation: 'Joel', ref_code: 'Joe'},
    { book_number: 30, book_name: 'Amos', num_chapters: 9, abbreviation: 'Amos', ref_code: 'Amo'},
    { book_number: 31, book_name: 'Obadiah', num_chapters: 1, abbreviation: 'Oba.', ref_code: 'Oba'},
    { book_number: 32, book_name: 'Jonah', num_chapters: 4, abbreviation: 'Jonah', ref_code: 'Jon'},
    { book_number: 33, book_name: 'Micah', num_chapters: 7, abbreviation: 'Micah', ref_code: 'Mic'},
    { book_number: 34, book_name: 'Nahum', num_chapters: 3, abbreviation: 'Nahum', ref_code: 'Nah'},
    { book_number: 35, book_name: 'Habakkuk', num_chapters: 3, abbreviation: 'Hab.', ref_code: 'Hab'},
    { book_number: 36, book_name: 'Zephaniah', num_chapters: 3, abbreviation: 'Zeph.', ref_code: 'Zep'},
    { book_number: 37, book_name: 'Haggai', num_chapters: 2, abbreviation: 'Hag.', ref_code: 'Hag'},
    { book_number: 38, book_name: 'Zechariah', num_chapters: 14, abbreviation: 'Zech.', ref_code: 'Zec'},
    { book_number: 39, book_name: 'Malachi', num_chapters: 4, abbreviation: 'Mal.', ref_code: 'Mal'},
    { book_number: 40, book_name: 'Matthew', num_chapters: 28, abbreviation: 'Matt.', ref_code: 'Mat'},
    { book_number: 41, book_name: 'Mark', num_chapters: 16, abbreviation: 'Mark', ref_code: 'Mar'},
    { book_number: 42, book_name: 'Luke', num_chapters: 24, abbreviation: 'Luke', ref_code: 'Luk'},
    { book_number: 43, book_name: 'John', num_chapters: 21, abbreviation: 'John', ref_code: 'Joh'},
    { book_number: 44, book_name: 'Acts', num_chapters: 28, abbreviation: 'Acts', ref_code: 'Act'},
    { book_number: 45, book_name: 'Romans', num_chapters: 16, abbreviation: 'Rom.', ref_code: 'Rom'},
    { book_number: 46, book_name: '1 Corinthians', num_chapters: 16, abbreviation: '1 Cor.', ref_code: 'FCo'},
    { book_number: 47, book_name: '2 Corinthians', num_chapters: 13, abbreviation: '2 Cor.', ref_code: 'SCo'},
    { book_number: 48, book_name: 'Galatians', num_chapters: 6, abbreviation: 'Gal.', ref_code: 'Gal'},
    { book_number: 49, book_name: 'Ephesians', num_chapters: 6, abbreviation: 'Eph.', ref_code: 'Eph'},
    { book_number: 50, book_name: 'Philippians', num_chapters: 4, abbreviation: 'Phil.', ref_code: 'Phi'},
    { book_number: 51, book_name: 'Colossians', num_chapters: 4, abbreviation: 'Col.', ref_code: 'Col'},
    { book_number: 52, book_name: '1 Thessalonians', num_chapters: 5, abbreviation: '1 Thes.', ref_code: 'FTh'},
    { book_number: 53, book_name: '2 Thessalonians', num_chapters: 3, abbreviation: '2 Thes.', ref_code: 'STh'},
    { book_number: 54, book_name: '1 Timothy', num_chapters: 6, abbreviation: '1 Tim.', ref_code: 'FTi'},
    { book_number: 55, book_name: '2 Timothy', num_chapters: 4, abbreviation: '2 Tim.', ref_code: 'STi'},
    { book_number: 56, book_name: 'Titus', num_chapters: 3, abbreviation: 'Titus', ref_code: 'Tit'},
    { book_number: 57, book_name: 'Philemon', num_chapters: 1, abbreviation: 'Philem.', ref_code: 'Phm'},
    { book_number: 58, book_name: 'Hebrews', num_chapters: 13, abbreviation: 'Heb.', ref_code: 'Heb'},
    { book_number: 59, book_name: 'James', num_chapters: 5, abbreviation: 'James', ref_code: 'Jam'},
    { book_number: 60, book_name: '1 Peter', num_chapters: 5, abbreviation: '1 Pet.', ref_code: 'FPe'},
    { book_number: 61, book_name: '2 Peter', num_chapters: 3, abbreviation: '2 Pet.', ref_code: 'SPe'},
    { book_number: 62, book_name: '1 John', num_chapters: 5, abbreviation: '1 John', ref_code: 'FJo'},
    { book_number: 63, book_name: '2 John', num_chapters: 1, abbreviation: '2 John', ref_code: 'SJo'},
    { book_number: 64, book_name: '3 John', num_chapters: 1, abbreviation: '3 John', ref_code: 'TJo'},
    { book_number: 65, book_name: 'Jude', num_chapters: 1, abbreviation: 'Jude', ref_code: 'Jde'},
    { book_number: 66, book_name: 'Revelation', num_chapters: 22, abbreviation: 'Rev.', ref_code: 'Rev'}
  ]
end
